name: Run lint checks


on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  # schedule:
    # - cron: '25 2 * * 4'

jobs:
  Run_lint_checks:
    name: Run eslint and prettier
    
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]
    
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"
      
      - name: 📦 Install dependencies
        run: npm install 

      # - name: 🚧 Set up project
        # run: npm dev:prepare

      - name: 🛠 Run prettier
        run: npm run format
      
      - name: 🛠 Run eslint
        run: npm run lint

      # - name: 🧪 Test project
        # run: npm test

      - name: 🟩 Coverage
        uses: codecov/codecov-action@v4



    

     
